// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AstroInvest",
  description: "Generated by create next app",
};

export default async function DashboarddRootLayout({ children }) {
  // Fetch the session from the server
  // const session = await getServerSession(authOptions);
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
        suppressHydrationWarning
      >
        {/* <SessionProviderWrapper session={session}> */}
          {children}
        {/* </SessionProviderWrapper> */}
        <Toaster />
      </body>
    </html>
  );
}
